### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [2]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call dir() on np.array.

Call dir() on car.

Note the difference. `car` has methods and attributes we can use.

In [6]:
### "Pip install pandas" in command line

# How can you get help on np.array?
?np.array # releases help window to get more information 

In [7]:
# Call dir() on np.array
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [8]:
# Call dir() on car
dir(car) # car has methods and attributes

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

 2.What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [13]:
print(car.dtype) # is an object

print(mpg.dtype) # is a float64

print(horsepower.dtype) # is a float64

print(origin.dtype) # is an object

object
float64
float64
object


3.`numpy` is often imported as `np`. What is this action called? Why might you do this? 

This action is called shortening a module. You might do this as a short-hand way to easily refer to the module you are using. This saves you time, so that you do not have to type "numpy" every time you call the module. 

4.Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [18]:
# Find the number of dimensions for each array

# car
print(car.ndim) # Only one dimension 

# mpg
print(mpg.ndim) # Only one dimension 

# cylinders
print(cylinders.ndim) # Only one dimension 

# displacement
print(displacement.ndim) # Only one dimension 

# horsepower
print(horsepower.ndim) # Only one dimension 

# weight
print(weight.ndim) # Only one dimension 

# acceleration
print(acceleration.ndim) # Only one dimension 

# model
print(model.ndim) # Only one dimension 

# origin
print(origin.ndim) # Only one dimension 

1
1
1
1
1
1
1
1
1


5.Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [33]:
#print(mpg)

# multiply the mpg array by 12.
mult_mpg = mpg*12
# print(mult_mpg)

# divide the mpg array by 3.
div_mpg = mpg/3
# print(div_mpg)

# raise the mpg array to the power of 4.
raise_mpg = mpg**4
#print(raise_mpg)

# take the square root of the mpg array.
sqrt_mpg = np.sqrt(mpg)
#print(sqrt_mpg)

6.What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [53]:
# sum
print("The sum of horsepower is " + str(sum(horsepower)))

# min
print("The minimum horsepower is " + str(min(horsepower)))

# max
print("The maximum horsepower is " + str(max(horsepower)))

# # median
print("The median horsepower is " + str(np.median(horsepower)))

The sum of horsepower is 42033.0
The minimum horsepower is 0.0
The maximum horsepower is 230.0
The median horsepower is 93.5


In [58]:
# Bonus: Find the mode

# need stats function from scipy module
from scipy import stats

# mode
mode_horsepower = stats.mode(horsepower)
print(mode_horsepower)

print("The mode for the horsepower array is 150, which appears 22 times")

ModeResult(mode=array([150.]), count=array([22]))
The mode for the horsepower array is 150, which appears 22 times


7.Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [63]:
# Print acceleration array
#print(acceleration)

# Select only the first 5 elements of the array
print(acceleration[0:5])
            # should output [12, 11.5, 11, 12, 10.5]

[12.  11.5 11.  12.  10.5]


In [64]:
# Select every other element (new selection)
print(acceleration[::2]) # slice operator to step by 2 (every other)

[12.  11.  10.5  9.  10.  17.5 11.  11.   8.   9.5 15.  15.5 14.5 17.5
 17.5 15.  15.  18.5 15.5 19.  13.  15.5 15.5 11.5 13.  12.  13.5 15.
 14.  19.5 19.  19.  15.5 23.5 16.5 12.  13.  11.  13.5 13.5 14.  14.
 18.  18.  17.  15.  13.  13.  12.5 12.  14.5 11.  16.5 16.  16.  14.
 13.  15.  19.5 13.5 14.  13.  19.5 14.  11.  13.5 16.5 16.  19.  21.
 17.  16.5 14.5 16.  16.5 14.5 19.  15.5 15.  16.  16.  19.5 14.  13.5
 18.5 19.  13.5 16.  16.  13.5 17.  14.  15.  14.5 17.5 16.9 17.7 13.
 13.9 15.4 17.6 22.2 14.2 17.7 16.2 12.2 16.4 15.7 21.9 16.7 12.  14.
 14.8 15.5 12.5 13.7 16.4 17.7 11.1 12.2 14.5 18.2 17.  16.4 14.5 13.5
 14.4 18.6 15.5 12.8 18.2 15.4 17.2 16.7 15.1 13.4 13.7 14.2 14.5 16.7
 14.9 13.6 15.8 16.6 18.2 18.2 15.4 13.2 14.9 15.  14.  14.4 20.1 24.8
 13.2 19.2 16.  12.9 14.7 15.5 16.5 20.1 15.8 17.5 15.2 14.4 21.7 19.9
 13.8 18.  11.4 15.1 17.  16.4 12.6 16.9 16.1 19.4 16.  16.2 14.2 14.4
 14.8 20.4 19.6 13.8 19.  16.6 18.6 16.2 18.  20.5 18.2 14.7 14.5 16.9
 15.7 16.4 1

8.Show how to select the number `99` in the array below. 

In [67]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [68]:
# Only select 99
select_99[1,2]

99

9.Select the last element in each subarray (do this with one operation.)

In [73]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [74]:
# Your code here
select_more[:,2]

array([3, 6, 9])

10.Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [76]:
# Searching for "log" with np.lookfor()
np.lookfor('log')

Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

In [82]:
# I selected numpy.logspace
# Apply to mpg
np.logspace(mpg, 0.5)

array([[1.00000000e+18, 1.00000000e+15, 1.00000000e+18, ...,
        1.00000000e+32, 1.00000000e+28, 1.00000000e+31],
       [4.39397056e+17, 5.05919749e+14, 4.39397056e+17, ...,
        2.27584593e+31, 2.74647411e+27, 2.38534401e+30],
       [1.93069773e+17, 2.55954792e+14, 1.93069773e+17, ...,
        5.17947468e+30, 7.54312006e+26, 5.68986603e+29],
       ...,
       [1.63789371e+01, 1.23548289e+01, 1.63789371e+01, ...,
        6.10540230e+01, 4.19226744e+01, 5.55773659e+01],
       [7.19685673e+00, 6.25055193e+00, 7.19685673e+00, ...,
        1.38949549e+01, 1.15139540e+01, 1.32571137e+01],
       [3.16227766e+00, 3.16227766e+00, 3.16227766e+00, ...,
        3.16227766e+00, 3.16227766e+00, 3.16227766e+00]])

11.You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [26]:
#type(origin)
origin_test = [0,6,5,0,6,5]


array([0, 5, 6])

12.
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

14.Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

15.Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

16.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

17.Transpose the following array. 

In [ ]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

Use numpy to answer the following questions. 

2.What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

3.On average are Japanse cars more fuel efficient than US cars? 

4.What is the correlation coefficient of `mpg` and `weight`? What is a correlaton coefficient?